### ISSUE TITLE
CMake based add-ons

### ISSUE THREAD

**Issue by notspiff** [garbear/peripheral.joystick#1]
Hi,

I have done a blind restructure to a cmake buildsystem for the addon at https://github.com/notspiff/peripheral.joystick

it still only handles the linux side, i am sure @Montellese will help with windows.

i cannot test it as your branch fails to build at the moment. JOYSTICK_BUTTONMAP is undefined.

**Comment by garbear** [comment]
thanks, you rock!

I copied the buildsys from xbmc-pvr-addons, only to realize too late that the CMake audio encoders stuff would have been the right way to go.

yesterday the API was mid-shuffle, I re-wrote most of it after my last [brainstorming session](http://forum.kodi.tv/showthread.php?tid=215414&pid=1896996#pid1896996). Things should compile now (JOYSTICK_BUTTONMAP has been totally removed) and the API has been synced with https://github.com/garbear/xbmc/tree/joysticks so the add-on should load in xbmc as well.

**Comment by notspiff** [comment]
confirmed. i built everything just fine now using https://github.com/notspiff/kodi-cmake/tree/peripheral_addons_garbear (which is your code on top of my master, it pulls in https://github.com/notspiff/peripheral.joystick)

**Comment by notspiff** [comment]
oh, and in case; there's no requirement of using my fork, i just gave the link for reference. the addon will work just as fine with mainline/your tree.

**Comment by garbear** [comment]
successfully moved peripheral.joystick to cmake build system
